name: Measure Test Flakiness

on: [push, pull_request]

permissions: read-all

jobs:
  measure-test-flakiness:
    name: Measure Test Flakiness
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
    - run: "./scripts/measure-test-flakiness.sh"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
