name: Robustness
on: [push, pull_request]
permissions: read-all
jobs:
  main:
    uses: ./.github/workflows/robustness-template.yaml
    with:
      etcdBranch: main
      count: 100
      testTimeout: 200m
      artifactName: main
  release-35:
    uses: ./.github/workflows/robustness-template.yaml
    with:
      etcdBranch: release-3.5
      count: 100
      testTimeout: 200m
      artifactName: release-35
  release-34:
    uses: ./.github/workflows/robustness-template.yaml
    with:
      etcdBranch: release-3.4
      count: 100
      testTimeout: 200m
      artifactName: release-34
