name: Tests-arm64
on:
  schedule:
    - cron: '30 1 * * *' # runs daily at 1:30 am.
jobs:
  test:
    # this is to prevent the job to run at forked projects
    if: github.repository == 'etcd-io/etcd'
    runs-on: [Linux, ARM64]
    strategy:
      fail-fast: false
      matrix:
        target:
        - linux-arm64-integration-1-cpu
        - linux-arm64-integration-2-cpu
        - linux-arm64-integration-4-cpu
        - linux-arm64-unit-4-cpu-race
    steps:
    - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0
    - uses: actions/setup-go@4d34df0c2316fe8122ab82dc22947d607c0c91f9 # v4.0.0
      with:
        ref: main
        go-version: "1.19.7"
    - run: date
    - env:
        TARGET: ${{ matrix.target }}
      run: |
        set -euo pipefail

        exit 0
    - uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3.1.2
      if: always()
      with:
        path: ./**/junit_*.xml
